# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.3
        with: 
          node-version: 12.x
      - name: build
        run: npm i && npm run build
      - name: aliyun-oss-website-action
        # You may pin to the exact commit or the version.
        # uses: fangbinwei/aliyun-oss-website-action@611f87b1701f12cb6790ff4f94ba76b7c8af3a52
        uses: fangbinwei/aliyun-oss-website-action@v1.2.1
        with:
          # Folder which contains the website files
          folder: ./build
          accessKeyId: LTAI4G1SaFV6AcsGYCDa1yAy
          # Aliyun OSS accessKeySecret.
          accessKeySecret: Q5agwqZl5YDgFvr1pLCxdJ9ISdi50A
          # Aliyun OSS bucket instance.
          bucket: wonderland-start
          # OSS region domain
          endpoint: oss-cn-shenzhen.aliyuncs.com
          # `true` to identify the endpoint is your custom domain.
